version: '3.4'

services:
  travelagencyapi:
    image: ${DOCKER_REGISTRY-}travelagencyapi
    build:
      context: .
      dockerfile: Test/Dockerfile
     
    ports:
        - "8080:80"
    depends_on:
        - TravelAgency
  TravelAgency:
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     ports:
       - "1433:1433"

     environment:
         SA_PASSWORD: "TestPassword123"
         ACCEPT_EULA: "Y"